version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: whatsapp-bot
    restart: always
    environment:
      POSTGRES_USER: doctorbee
      POSTGRES_PASSWORD: baba2003
      POSTGRES_DB: whatsapp-bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
